### ISSUE TITLE
README.md references non-existing src/test directory

### ISSUE THREAD

**Issue by mbanck** [UFParLab/acesinit#5]
The README.md says in the section "To Use" that the user should "Copy all the files in src/test and the acesinit executable to a separate directory", however `src/test` does not exist.

**Comment by madbosun** [comment]
Try the master branch now.  Some one who will remain nameless dumped those files out and never updated them to reflect the current Aces4 flow.

There needs to be at some point example ZMAT files reflecting all of the Sial_QM tests in Aces4.
